library(knitr)
library(markdown)
library(ggvis)
library(dplyr)
library(rvest)
library(gsubfn)
library(tidyr)
library(shiny)
library(readr)
library(dplyr)
library(ggplot2)
library(gtable)
library(tmap)
library(StandardizeText)
library(sf)
library(rdal)
library(maptools)
library(rgeos)
library(tmap)
library(rnaturalearth)
library(plotly)
library(useful)
library(gridExtra)
library(grid)
library(scales)
library(stats)


# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")

